### ISSUE TITLE
Republish as `babel-plugin-jest-assertions`

### ISSUE THREAD

**Issue by mikestopcontinues** [mattphillips/babel-jest-assertions#16]
Hi, I love the plugin, but because it doesn't match babel plugin naming convention, I have to add it to my config like so:

```json
{
  "plugins": ["./node_modules/babel-jest-assertions"]
}
```

If the naming was changed, we could just write: 

```json
{
  "plugins": ["jest-assertions"]
}
```

Thanks!

**Comment by epodivilov** [comment]
It may be quite late, but you can still connect the plugin differently
```json
{
  "plugins": ["module:babel-jest-assertions"]
}
```

**Comment by mikestopcontinues** [comment]
I've mostly moved off babel now, but thanks. :)
