### ISSUE TITLE
Count assertions in before/afterEach

### ISSUE THREAD

**Issue by giuseppeg** [mattphillips/babel-jest-assertions#6]
**Feature Request**

Description:

This is a nit feature request. It'd be cool if assertions made in `beforeEach` and `afterEach` were included in the count.

Possible solution:

Traverse upwards the AST and collect `expects` defined in `beforeEach` and `afterEach`

**Comment by mattphillips** [comment]
Hey @giuseppeg thanks for the feature request! I've just published support for this in v0.1.0 if you can check it out and let me know if it works as expected (pun intended 😛) that would be great!

**Comment by giuseppeg** [comment]
@mattphillips sweet! Thank you so much for implementing this. I have a huge WIP branch at work which I can use to test this. The bad news is that I am on vacation so I will get back to it later in January. I took a look at the tests though and lgtm ✌️

**Comment by mattphillips** [comment]
Awesome let me know if you run into any issues with it! Enjoy your vacation dude :smile:
